"""empty message

Revision ID: c4cdbf89a8ab
Revises: bdf22fdb189d
Create Date: 2023-02-05 20:23:40.460164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4cdbf89a8ab'
down_revision = 'bdf22fdb189d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contraseña', sa.String(length=120), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('contraseña')

    # ### end Alembic commands ###
